# Site settings
author: Nicholas Patel
title: CLI Project OOF
header-img: img/home-bg.png
email: np4795@yahoo.com
copyright_name: Nicholas Patel
description: > # this means to ignore newlines until "baseurl:"
  CLI project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  np4795

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
